Exception in Tkinter callback
Traceback (most recent call last):
<<<<<<< HEAD
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 145, in loadgeom
    f=open(self.geofilename,'r')
IOError: [Errno 2] No such file or directory: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 196, in syntaxCheck
    int(self.nwinding.get())
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 196, in syntaxCheck
    int(self.nwinding.get())
ValueError: invalid literal for int() with base 10: ''
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 204, in syntaxCheck
    float(self.gb.get())
ValueError: could not convert string to float: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 204, in syntaxCheck
    float(self.gb.get())
ValueError: could not convert string to float: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 204, in syntaxCheck
    float(self.gb.get())
ValueError: could not convert string to float: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 204, in syntaxCheck
    float(self.gb.get())
ValueError: could not convert string to float: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 204, in syntaxCheck
    float(self.gb.get())
ValueError: could not convert string to float: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 208, in syntaxCheck
    float(self.Ae.get())
ValueError: invalid literal for float(): 60e-2,1e-3
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 208, in syntaxCheck
    float(self.Ae.get())
ValueError: invalid literal for float(): 60e-2,1e-3
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 208, in syntaxCheck
    float(self.Ae.get())
ValueError: invalid literal for float(): 60e-2,1e-3
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "gui.py", line 155, in checkgeom
    self.syntaxCheck()
  File "gui.py", line 208, in syntaxCheck
    float(self.Ae.get())
ValueError: invalid literal for float(): 60e-2,1e-3
=======
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1473, in __call__
    return self.func(*args)
  File "gui.py", line 545, in generate_netlist_errors
    except e:
NameError: global name 'e' is not defined
>>>>>>> upstream/master
